resource "uptimerobot_monitor" "heartbeat" {
  name         = "My Service Heartbeat"
  type         = "HEARTBEAT"
  interval     = 300
  grace_period = 900

  # Optional: Tags for organization
  tags = ["production", "web"]
}
# The heartbeat URL is generated by UptimeRobot and available as:
# uptimerobot_monitor.heartbeat.url
